name: Blue-Green ECS Deployment
description: Performs blue-green deployment using ALB, ECS, and two target groups (A/B).
author: Yushin Son

inputs:
  environment:
    description: Environment name
    required: true
  image-tag:
    description: Docker image tag
    required: true
  ecr-uri:
    description: ECR URI
    required: true
  cluster-name:
    description: Name of the ECS cluster
    required: true
  task-def-name:
    description: Name of the task definition
    required: true
  listener-arn:
    description: ARN of the ALB listener
    required: true
  tg-a-name:
    description: ARN of target group A
    required: true
  tg-b-name:
    description: ARN of target group B
    required: true
  service-a-name:
    description: Name of ECS service A
    required: true
  service-b-name:
    description: Name of ECS service B
    required: true
  
 

runs:
  using: "composite"
  steps:
    - name: Set executable permission
      run: chmod +x ${{ github.action_path }}/deploy-bluegreen.sh
      shell: bash

    - name: Run blue-green deploy script
      run: |
        ${{ github.action_path }}/deploy-bluegreen.sh \
          "${{ inputs.environment }}" \
          "${{ inputs.image-tag }}" \
          "${{ inputs.ecr-uri }}" \
          "${{ inputs.cluster-name }}" \
          "${{ inputs.task-def-name }}" \
          "${{ inputs.listener-arn }}" \
          "${{ inputs.tg-a-name }}" \
          "${{ inputs.tg-b-name }}" \
          "${{ inputs.service-a-name }}" \
          "${{ inputs.service-b-name }}"
      shell: bash
